# Recuerde poner aqui los datos de conexion y guardar como SecretConfig.py

PGHOST='PONGA EL HOST DE RENDER AQUI'
PGDATABASE='PONGA EL NOMBRE DE LA BD AQUI'
PGUSER='PONGA EL USUARIO AQUI'
PGPASSWORD='PONGA LA CONTRASEÑA AQUI'
PGPORT=5432